# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run_dashboard.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'), 
        ('static', 'static'), 
        ('requirements.txt', '.'), 
        ('monitor_config.json', '.'), 
        ('logo-1-1.webp', 'static'),
        ('system_lock_overlay.py', '.'),
        ('app_blocker.py', '.'),
        ('screenshot_taker.py', '.'),
        ('webcam_capture.py', '.'),
        ('keystroke_logger_by_app.py', '.'),
        ('activity_tracker.py', '.'),
        ('app_usage_tracker.py', '.'),
        ('audio_monitor.py', '.'),
        ('file_transfer_monitor.py', '.'),
        ('internet_monitor.py', '.'),
        ('usb_monitor.py', '.'),
        ('website_tracker.py', '.'),
        ('check_network.py', '.'),
        ('live_monitor.py', '.'),
        ('LocalMonitorWeb.py', '.')
    ],
    hiddenimports=[
        'PIL._tkinter_finder',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'subprocess',
        'os',
        'sys',
        'threading',
        'time',
        'datetime',
        'json',
        'psutil',
        'pynput',
        'keyboard',
        'mouse',
        'pywin32',
        'mss',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'cv2',
        'watchdog',
        'requests',
        'netifaces',
        'pyngrok',
        'PyAudio',
        'sounddevice',
        'tkcalendar',
        'humanize',
        'pyautogui',
        'python-dateutil',
        'numpy',
        'shutil',
        'logging',
        'flask',
        'werkzeug',
        'flask_login',
        'flask_socketio'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Changed to True for debugging
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
)
